#%RAML 0.8
---
title: "RAML exercise with JAX-RS"
version: v1
schemas:
  - user: !include user.json
  - users: !include users.json
/users:
  get:
    description: Retrieve all users
    responses:
      200:
        body:
          application/json:
            schema: users
  /{userId}:
    get:
      description: Retrieve a user which has specified ID
      responses:
        200:
          body:
            application/json:
              schema: user